# Generated by Django 4.1.1 on 2023-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='event_id',
            field=models.TextField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='user_id',
            field=models.TextField(default=0, max_length=10),
        ),
    ]
