# Generated by Django 4.1.1 on 2023-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0002_eventuser_event_id_eventuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_creator_id',
            field=models.TextField(default=0, max_length=10),
        ),
    ]
