# Generated by Django 4.1.1 on 2023-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0004_event_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='event_pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
