# Generated by Django 4.1.1 on 2023-01-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0007_rename_user_event_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='username',
        ),
    ]
