# Generated by Django 4.1.1 on 2023-01-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0008_remove_event_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('plan_short_description', models.CharField(max_length=200, null=True)),
                ('plan_full_description', models.TextField(max_length=1000, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
