# Generated by Django 4.1.1 on 2023-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0009_eventplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
