# Generated by Django 4.1.1 on 2023-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elists', '0010_eventplan_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='plan_full_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='plan_short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
